version: 2

build:
   os: ubuntu-latest
   tools:
      python: "3.12"
   jobs:
      post_create_environment:
         - python -m pip install poetry
      post_install:
         - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs

sphinx:
   configuration: docs/conf.py
   builder: dirhtml

formats: all
